github.com:
    git_protocol: ssh
    users:
        vcntttt:
            oauth_token: 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
    user: vcntttt
    oauth_token: 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
