input {
  kb_layout = us
}

monitorv2 {
  output = HDMI-A-1
  mode = 1920x1080@144
  position = 0x0
  scale = 1
}

monitorv2 {
  output = DP-1
  mode = 1920x1080@144
  position = auto-right
  scale = 1
}

monitorv2 {
  output = HDMI-A-2
  mode = 3840x2160@29.97
  position = auto-right
  scale = 1
}

exec-once = [workspace 1] zen-browser
exec-once = [workspace 4 silent] vesktop
exec-once = [workspace 4 silent; group set always] betterbird
exec-once = [workspace 8 silent] obsidian
exec-once = [workspace 9 silent] spotify-launcher
