input {
  kb_layout = es
  accel_profile = adaptive
  sensitivity = 0
  touchpad {
    natural_scroll = true
    scroll_factor = 0.6
  }
}



monitor = eDP-1, preferred, auto, 1
env = GDK_SCALE,2
env = GDK_DPI_SCALE,2
