input {
  kb_layout = latam
  accel_profile = adaptive
  sensitivity = 0
  touchpad {
    natural_scroll = true
    scroll_factor = 0.4
  }
}

monitor = eDP-1, preferred, auto, 1.2

exec-once = [workspace 1] zen-browser
exec-once = [workspace 4 silent] betterbird
