#! /bin/sh

chosen=$(printf "Power Off\nRestart\Lock" | rofi -dmenu -i -theme-str '@import "power.rasi"'

case "$chosen" in
	"Power Off") poweroff ;;
	"Restart") reboot ;;
	"Lock") slock ;;
	*) exit 1 ;;
esac