config_version = 8

[bar.default]
capsule = true
capsule_fill = "surface_variant"
capsule_opacity = 1.0
capsule_padding = 6.0
capsule_radius = 8.0
center = [ "active_window" ]
end = [ "group:g1", "spacer_1", "tray", "network", "galileo", "volume", "clock", "notifications" ]
start = [ "widget", "workspaces", "media", "layout" ]
widget_spacing = 8.0

[brightness]
enable_ddcutil = true
minimum_brightness = 0.099999997764825821

[lockscreen_widgets]
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 960.0
    cy = 889.5
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 960.0
    cy = 889.5
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

[osd]
offset_y = 40
position = "bottom_center"
position_vertical = "bottom_center"

[plugin_settings."yuuto/arch-updater"]
auto_check_hours = 1

[plugins]
enabled = [
    "vrivera/display-controls",
    "vrivera/galileo",
    "vrivera/layout-controls",
    "yuuto/arch-updater",
    "vrivera/audio-output"
]

[shell]
telemetry_enabled = true

    [shell.mpris]
    blacklist = [ "firefox" ]

[theme]
builtin = "Noctalia"
community_palette = "Ayu Blue"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "ghostty", "hyprland", "kcolorscheme", "kitty", "qt", "starship" ]
    community_ids = [ "pi-agent", "neovim", "bat", "lazygit", "yazi" ]

[wallpaper]
directory = "/home/vrivera/Imágenes/wallpapers/"

    [wallpaper.default]
    path = "/home/vrivera/Imágenes/wallpapers/fantasy-city.jpg"

    [wallpaper.last]
    path = "/home/vrivera/Imágenes/wallpapers/fantasy-city.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/vrivera/Imágenes/wallpapers/fantasy-city.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/vrivera/Imágenes/wallpapers/fantasy-city.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/vrivera/Imágenes/wallpapers/catching-the-desert.jpeg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-tonal-spot"

[widget.layout]
type = "vrivera/layout-controls:layout"

[widget.spacer_1]
enabled = false

[widget.widget]
type = "yuuto/arch-updater:widget"